title: Blog MiSter
tagline: Sterowniki programowalne • Montaż SMD/THT • Elektronika na zamówienie
description: >-
  Aktualności, porady techniczne i realizacje z zakresu projektowania urządzeń elektronicznych, montażu kontraktowego SMT/THT oraz programowania mikrokontrolerów.

baseurl: "/mister-blog"
url: "https://mi-sterwp.github.io"

remote_theme: cotes2020/jekyll-theme-chirpy

lang: pl
timezone: Europe/Warsaw

# Logo
avatar: /assets/img/logo/MiSter_logo_RGB_50.png

github: Mi-SterWP

# Wygląd
theme_mode: dark

# Dodatkowe ustawienia Chirpy
paginate: 10
paginate_path: "page/:num"
future: true

# Wymagane wtyczki
