title: Blog MiSter
tagline: Sterowniki programowalne • Montaż SMD/THT • Elektronika na zamówienie
description: >-
  Aktualności, porady techniczne i realizacje z zakresu projektowania urządzeń elektronicznych, montażu kontraktowego SMT/THT oraz programowania mikrokontrolerów.

# === WAŻNE DLA TWOJEGO REPO ===
baseurl: "/mister-blog"          # <--- to jest najważniejsze
url: "https://mi-sterwp.github.io"

remote_theme: cotes2020/jekyll-theme-chirpy

lang: pl
timezone: Europe/Warsaw

# Logo
avatar: /assets/img/logo/MiSter_logo_RGB_50.png

github: Mi-SterWP

theme_mode: dark
future: true
incremental: false

paginate: 10
paginate_path: "page/:num"
